runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
#- url: /static
#  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /store
  script: auto

- url: /fetchMany
  script: auto

- url: /fetchAll
  script: auto

- url: /fetchKeys
  script: auto

- url: /deleteMany
  script: auto

- url: /filterMany
  script: auto

env_variables:
  KIND: "dropzoneDatastore"
  USERNAME: "luffy"
  PASSWORD: "Qn94vt--a^eNHKK7"
  FLASK_ENV: production
  FLASK_APP: main.py
  
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50